//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soap_Winform.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void startSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/startSession", ReplyAction="*")]
        System.Threading.Tasks.Task startSessionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataset(string connStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataset", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDatasetAsync(string connStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOneDataset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOneDataset(string connStr, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOneDataset", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOneDatasetAsync(string connStr, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddData(string connStr, string name, string surname, int age, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddData", ReplyAction="*")]
        System.Threading.Tasks.Task AddDataAsync(string connStr, string name, string surname, int age, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateData(string connStr, int id, string name, string surname, int age, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateDataAsync(string connStr, int id, string name, string surname, int age, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteData(string connStr, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteData", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteDataAsync(string connStr, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSessionTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSessionTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSessionTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSessionTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Soap_Winform.ServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Soap_Winform.ServiceReference.WebService1Soap>, Soap_Winform.ServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void startSession() {
            base.Channel.startSession();
        }
        
        public System.Threading.Tasks.Task startSessionAsync() {
            return base.Channel.startSessionAsync();
        }
        
        public System.Data.DataSet GetDataset(string connStr) {
            return base.Channel.GetDataset(connStr);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDatasetAsync(string connStr) {
            return base.Channel.GetDatasetAsync(connStr);
        }
        
        public System.Data.DataSet GetOneDataset(string connStr, int id) {
            return base.Channel.GetOneDataset(connStr, id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOneDatasetAsync(string connStr, int id) {
            return base.Channel.GetOneDatasetAsync(connStr, id);
        }
        
        public void AddData(string connStr, string name, string surname, int age, string location) {
            base.Channel.AddData(connStr, name, surname, age, location);
        }
        
        public System.Threading.Tasks.Task AddDataAsync(string connStr, string name, string surname, int age, string location) {
            return base.Channel.AddDataAsync(connStr, name, surname, age, location);
        }
        
        public void UpdateData(string connStr, int id, string name, string surname, int age, string location) {
            base.Channel.UpdateData(connStr, id, name, surname, age, location);
        }
        
        public System.Threading.Tasks.Task UpdateDataAsync(string connStr, int id, string name, string surname, int age, string location) {
            return base.Channel.UpdateDataAsync(connStr, id, name, surname, age, location);
        }
        
        public void DeleteData(string connStr, int id) {
            base.Channel.DeleteData(connStr, id);
        }
        
        public System.Threading.Tasks.Task DeleteDataAsync(string connStr, int id) {
            return base.Channel.DeleteDataAsync(connStr, id);
        }
        
        public string getSessionTime() {
            return base.Channel.getSessionTime();
        }
        
        public System.Threading.Tasks.Task<string> getSessionTimeAsync() {
            return base.Channel.getSessionTimeAsync();
        }
    }
}
